spring:
  profiles:
    active: local
---
spring:
  application:
    name: skincare-diary-spring-boot
  profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/skincarediary
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

springdoc:
  swagger-ui:
    path: /api-docs

logging:
  level:
    root: DEBUG
