spring:
  profiles:
    active: local
---
spring:
  application:
    name: skincare-diary-spring-boot
  profile: local
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  # liquibase:
  #   change-log: classpath:db/changelog/changelog-master.xml
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
